#!/usr/bin/python3

import os.path
import sys
fn=sys.argv[1:]

for i in fn:
    if os.path.isfile(i):
        f=open(i,'a+')
        f.close()

    else:
        f=open(i,'w')
        f.close()
        
